name: Prova
favicon: null
layout_spectrum: 0.9629
typography_spectrum: 0.48963112267665565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.875
  lightness: 0.9953533667139709
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
